baseURL = 'https://emotionsindrama.github.io/'
# languageCode = 'en-us'
title = 'Emotions in Drama'
author = 'Thomas Schmidt and Sarah Kurek'
theme = 'bootstrap-bp-hugo-theme'
enableInlineShortcodes = true
disableLanguages = 'de'

[Author]  
  name = "Thomas Schmidt and Sarah Kurek"

[params]
    alwaysExpandMenu = true
    hideReadingTime = true

[languages]
    [languages.en]
        languageName = "English"
        contentDir = "content/english"
        title = "Emotions in Drama"
        weight = 1
        
        


        [[languages.en.menu.footer]]
            identifier = "imprint"
            name = "Imprint"
            url = "https://www.uni-regensburg.de/impressum/startseite/index.html"
            weight = 10

        [[languages.en.menu.footer]]
            identifier = "privacy"
            name = "Privacy"
            url = "https://www.uni-regensburg.de/datenschutz/startseite/index.html"
            weight = 20

    [languages.de]
        languageName = "Deutsch"
        contentDir = "content/german"
        title = "Emotionen in Dramen"
        weight = 2
        
        [languages.de.menu]
        [[languages.de.menu.main]]
            identifier = "info"
            name = "Info"
            url = "/de/info/"
            weight = 10
            
        [[languages.de.menu.main]]
            identifier = "autoren"
            name = "Autoren"
            url = "/de/autoren/"
            weight = 20

        [[languages.de.menu.main]]
            identifier = "publikationen"
            name = "Publikationen"
            url = "/de/publikationen/"
            weight = 30
            
        [[languages.de.menu.footer]]
            identifier = "impressum"
            name = "Impressum"
            url = "https://www.uni-regensburg.de/impressum/startseite/index.html"
            weight = 10

        [[languages.de.menu.footer]]
            identifier = "datenschutz"
            name = "Datenschutz"
            url = "https://www.uni-regensburg.de/datenschutz/startseite/index.html"
            weight = 10


[social]
  # Social Links with corresponding Icons
  # for further options see https://github.com/spech66/bootstrap-bp-hugo-theme#social-icons

  twitter          = "search?q=%23EmoDrama&src=typed_query&f=live"
  # github           = ""
